# Generated by Django 6.1.1 on 2026-09-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('answer', models.TextField()),
                ('practiced', models.BooleanField(default=False)),
            ],
        ),
    ]
