# Generated by Django 6.1.1 on 2026-09-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('score', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('practiced_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
